# Generated by Django 5.1.2 on 2025-01-01 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_uploadedfile_user_chathistory_delete_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='chat_name',
            field=models.CharField(default='New Chat', max_length=255),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='app.user'),
        ),
    ]
